############################ Default configuration #########################
baseURL = "https://sedat.netlify.app/"
languageCode = "tr-TR"
# languageCode = "en-us"
# site title
title = "Sedat ERGÖZ | Personal Blog"
# theme
theme = "northendlab-light"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

[outputs]
home = ["HTML", "AMP", "RSS", "JSON", "SITEMAP"]
page = ["HTML"]


########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

########################### Navigation ###################################

# main menu
# [[menu.main]]
# URL = "https://c.sedat.cf/s/PsAaxmsQ5sNFWPe"
# name = "Shared Files"
# weight = 1

# [[menu.main]]
# URL = "https://service.sedat.cf/status/services"
# name = "Service Status"
# weight = 1

[[menu.main]]
URL = "https://sedat.netlify.app"
name = "Home"
weight = 1

# [[menu.main]]
# URL = "https://github.com/eaeoz"
# name = "Github"
# weight = 2

# [[menu.main]]
# URL = "https://www.linkedin.com/in/sedat-ergoz-604527346/"
# name = "Linkedin"
# weight = 1

# footer menu
[[menu.footer]]
URL = "mailto:sedatergoz@gmail.com"
name = "Contact"
weight = 1

[[menu.footer]]
URL = "privacy"
name = "Privacy"
weight = 1

[[menu.footer]]
URL = "termsandconditions"
name = "Terms"
weight = 1


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo5.svg"
# meta data
author = "Sedat ERGOZ"
description = "Teknoloji, yazılım, sağlık ve yaşam üzerine yazılar. Dark tema, modern tasarım ve kişisel blog yazıları."
# google tag manager
google_tag_manager = "G-1X79JXJNE9" # your id
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
# copyright = "&copy; 2025 [Sedat ERGÖZ](/author/sedat/) All Rights Reserved"
copyright = "Sedat Personal Blog"
# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2

####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = ""
image = "images/banner/illustration.svg"

######################## call to action ###############################
#[params.cta]
#enable = true
#image = "images/qr.svg"
# title = " _    _"
# description = " _    Scan Code for Android App"
# [params.cta.button]
# enable = true
# label = "Send"
# link = "mailto:sedatergoz@gmail.com"

############################## Social Site ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
#link = "#"
#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
#link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/eaeoz"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/sedat-ergoz-604527346/"
