[build]
  publish = "public"
  command = "hugo --minify --gc"

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_BASEURL = "/"

[functions]
  node_bundler = "esbuild"
  external_node_version = "20"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[plugins]]
  package = "@netlify/plugin-sitemap"

    [plugins.inputs]
      buildDir = "public"
      exclude = [
        # By file Path
        './404.html',
        # By Glob pattern
        './amp*',
        './google*'
      ]
